"""
Mumbai Local Railway — Fare Data Exporter
Generates the complete fare matrix in three formats:
  1. fare_matrix.json          → {from: {to: fare}} nested JSON
  2. fare_list.json            → [{from, to, fare}, …] flat list (MongoDB-ready)
  3. fare_matrix.py            → Python dict literal (importable)

Run:
    python export_fares.py
"""

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from data.stations import STATIONS, FARE_LOOKUP, export_fare_dict, export_fare_list

OUT = Path(__file__).parent / "fare_data"
OUT.mkdir(exist_ok=True)

# ── 1. Nested JSON  {from_name: {to_name: fare}} ─────────────────────────────
nested = export_fare_dict()
with open(OUT / "fare_matrix.json", "w", encoding="utf-8") as f:
    json.dump(nested, f, indent=2, ensure_ascii=False)
print(f"[OK] fare_matrix.json  — {len(nested)} stations")

# ── 2. Flat list  [{from, to, fare}]  (MongoDB / pandas-ready) ───────────────
flat = export_fare_list()
with open(OUT / "fare_list.json", "w", encoding="utf-8") as f:
    json.dump(flat, f, indent=2, ensure_ascii=False)
print(f"[OK] fare_list.json    — {len(flat)} unique pairs")

# ── 3. Python dict literal ────────────────────────────────────────────────────
id_to_name = {s["id"]: s["name"] for s in STATIONS}
lines = [
    "# Mumbai Local Railway — Official-like Fare Matrix",
    "# Auto-generated by export_fares.py",
    "# Usage: from fare_data.fare_matrix import FARE_MATRIX",
    "#        fare = FARE_MATRIX['Churchgate']['Andheri']  # → 20",
    "",
    "FARE_MATRIX = {",
]
for from_name, destinations in sorted(nested.items()):
    lines.append(f'    {from_name!r}: {{')
    for to_name, fare in sorted(destinations.items()):
        lines.append(f'        {to_name!r}: {fare},')
    lines.append('    },')
lines.append("}")

with open(OUT / "fare_matrix.py", "w", encoding="utf-8") as f:
    f.write("\n".join(lines))
print(f"[OK] fare_matrix.py    — Python dict literal")

# ── 4. Summary stats ──────────────────────────────────────────────────────────
fares = [r["fare"] for r in flat]
print(f"\n{'─'*50}")
print(f"  Total stations  : {len(STATIONS)}")
print(f"  Total pairs     : {len(flat)}")
print(f"  Fare range      : ₹{min(fares)} – ₹{max(fares)}")
from collections import Counter
dist = Counter(fares)
print(f"  Distribution    :")
for fare in sorted(dist):
    bar = "█" * (dist[fare] * 40 // max(dist.values()))
    print(f"    ₹{fare:>3}  {bar:<42} {dist[fare]} pairs")
print(f"{'─'*50}")

# ── 5. Sample lookups ─────────────────────────────────────────────────────────
print("\n  Sample fares (from fare_matrix.json):")
samples = [
    ("Churchgate",   "Andheri"),
    ("Churchgate",   "Borivali"),
    ("Churchgate",   "Virar"),
    ("CSMT",         "Thane"),
    ("CSMT",         "Kalyan"),
    ("CSMT",         "Kasara"),
    ("CSMT (Harbour)","Panvel"),
    ("Thane (TH)",   "Panvel (TH)"),
    ("Bandra",       "Dadar"),
    ("Andheri",      "Goregaon"),
]
for frm, to in samples:
    fare = nested.get(frm, {}).get(to, "N/A")
    print(f"    {frm:<22} → {to:<22}  ₹{fare}")

print(f"\n  Files saved to: {OUT.resolve()}\n")
